package com.sakurageto.card

import com.sakurageto.gamelogic.GameStatus

class Text(
    val timing_tag: TextEffectTimingTag, val tag: TextEffectTag, val effect:
    (suspend (Int, PlayerEnum, GameStatus, MadeAttack?) -> Int?)?
)

enum class TextEffectTimingTag {
    CONSTANT_EFFECT,
    AFTER_DESTRUCTION,
    START_DEPLOYMENT,
    IN_DEPLOYMENT,
    USED,
    USING,
    AFTER_ATTACK,
}

enum class TextEffectTag {
    NEXT_ATTACK_ENCHANTMENT,
    NEXT_ATTACK_ENCHANTMENT_OTHER,
    CHANGE_CONCENTRATION,
    CHASM,
    MAKE_ATTACK,
    MOVE_SAKURA_TOKEN,
    IMMEDIATE_RETURN,
    RETURN,
    TERMINATION,
    USING_CONDITION,
    DO_NOT_NAP,
    THIS_CARD_NAP_LOCATION_CHANGE,
    CAN_REACTABLE,
    REACT_ATTACK_REDUCE,
    REACT_ATTACK_NO_DAMAGE,
    REACT_ATTACK_INVALID,
    GAME_END,
    DRAW_CARD,
    CARD_TO_COVER,
    ADJUST_NAP,
    COST_BUFF,
    COST_X,
    CHANGE_SWELL_DISTANCE,
    DAMAGE_AURA_REPLACEABLE_HERE,
    MAKE_SHRINK,
    FORBID_MOVE_TOKEN,
    CARD_DISCARD_PLACE_CHANGE,
    MOVE_CARD,
    RECONSTRUCT,
    INSTALLATION,
    INSTALLATION_INFINITE,
    USE_CARD,
    RETURN_OTHER_CARD,
    END_TURN_EFFECT,
    SHOW_HAND_WHEN_CHANGE_UMBRELLA,
    EFFECT_WHEN_DESTRUCTION_OTHER_CARD,
    SEAL_CARD,
    EFFECT_INSTEAD_DAMAGE,
    ADD_LOG,
    INSERT_POISON,
    CHANGE_DISTANCE,
    FORBID_GO_BACKWARD_OTHER,
    FORBID_BREAK_AWAY,
    END_CURRENT_PHASE,
    CAN_NOT_USE_ATTACK,
    ADD_LISTENER,
    DAMAGE,
    CAN_USE_COVER,
    RUN_STRATAGEM;
}