package com.sakurageto.card

import com.sakurageto.gamelogic.GameStatus

class Text(
    val timing_tag: TextEffectTimingTag, val tag: TextEffectTag, val effect:
    (suspend (Int, PlayerEnum, GameStatus, MadeAttack?) -> Int?)?
)

enum class TextEffectTimingTag {
    CONSTANT_EFFECT,
    AFTER_DESTRUCTION,
    START_DEPLOYMENT,
    IN_DEPLOYMENT,
    USED,
    USING,
    AFTER_ATTACK,
}

enum class TextEffectTag {
    //basic tag that exist in real game
    CHASM,
    RETURN,
    TERMINATION,
    IMMEDIATE_RETURN,

    //Special megami effect
    WHEN_MANEUVER,
    TRANSFORM,
    MANEUVER,
    CHANGE_RAIRA_GAUGE,
    INSTALLATION,
    INSTALLATION_INFINITE,
    RUN_STRATAGEM,

    //just define what this effect do
    DAMAGE,
    RECONSTRUCT,
    REACT_ATTACK_CHANGE,
    REACT_ATTACK_NO_DAMAGE,
    REACT_ATTACK_INVALID,
    DRAW_CARD,
    USE_CARD,
    MOVE_CARD,
    CHANGE_CONCENTRATION,
    MAKE_ATTACK,
    MOVE_SAKURA_TOKEN,
    RETURN_OTHER_CARD,
    MAKE_SHRINK,
    ADD_LISTENER,
    SEAL_CARD,
    CARD_DISCARD_PLACE_CHANGE,
    ADD_LOG,
    INSERT_POISON,
    CHANGE_THIS_TURN_DISTANCE,
    CHANGE_THIS_TURN_SWELL_DISTANCE,
    GAME_END,
    END_CURRENT_PHASE,

    //description when this effect use
    WHEN_USE_BEHAVIOR_END,
    WHEN_SPECIAL_RETURN_YOUR,
    WHEN_FULL_POWER_USED_YOUR,
    WHEN_END_PHASE_YOUR,
    WHEN_THIS_CARD_RETURN,
    WHEN_CHOOSE_AURA_DAMAGE,
    WHEN_TRANSFORM,
    WHEN_DEPLOYMENT_OTHER,
    WHEN_ENCHANTMENT_DESTRUCTION_YOUR,
    WHEN_GET_DAMAGE_BY_ATTACK,

    //description when this effect use this is exist in real game
    WHEN_START_PHASE_YOUR,

    //check effect when some process is running
    FORBID_BASIC_OPERATION,
    NEXT_ATTACK_ENCHANTMENT,
    NEXT_ATTACK_ENCHANTMENT_OTHER,
    USING_CONDITION,
    DO_NOT_NAP,
    THIS_CARD_NAP_LOCATION_CHANGE,
    CAN_REACTABLE,
    ADJUST_NAP,
    COST_BUFF,
    COST_X,
    CHANGE_SWELL_DISTANCE,
    DAMAGE_AURA_REPLACEABLE_HERE,
    FORBID_MOVE_TOKEN,
    SHOW_HAND_WHEN_CHANGE_UMBRELLA,
    EFFECT_INSTEAD_DAMAGE,
    CHANGE_DISTANCE,
    FORBID_GO_BACKWARD_OTHER,
    FORBID_BREAK_AWAY_OTHER,
    CAN_NOT_USE_ATTACK,
    CAN_USE_COVER,
    COST_CHECK,
    COST,
    AFTER_AURA_DAMAGE_PLACE_CHANGE,
    AFTER_LIFE_DAMAGE_PLACE_CHANGE,
    AFTER_OTHER_ATTACK_COMPLETE,
    AFTER_ATTACK_EFFECT_INVALID_OTHER,
    AFTER_DESTRUCTION_EFFECT_INVALID_OTHER;
}