package com.sakurageto.gamelogic

enum class CardEffectLocation {
    EFFECT_LACERATION,
    ARTIFICIAL_TOKEN,
    ENCHANTMENT_OTHER,
    ENCHANTMENT_YOUR,
    DISCARD_YOUR,
    RETURN_YOUR,
    USED_YOUR,
    USED_OTHER,
    MEGAMI_YOUR,
    DIVING,
    TEMP_PLAYER1,
    TEMP_PLAYER2,
    IDEA_PLAYER1,
    IDEA_PLAYER2;
}